id: P005405
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18682
  title: དཔོན་པོའི་གསུང་རབ།
  author: ''
  volumes:
    441da33613444d6a9e6b6fab3a7abc13:
      image_group_id: I8LS18684
      title: ''
      volume_number: 1
      total_pages: 55
