id: I4574AB07
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:57:46+00:00'
last_modified: '2022-06-08T02:51:10.661838+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18682
  title: དཔོན་པོའི་གསུང་རབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    550E:
      image_group_id: I8LS18684
      title: ''
      total_pages: 55
      order: 1
      base_file: 550E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
